AWS_ACCESS_KEY_ID_IMPORTS = "AKIRJWM3B337FI6CARVQ"
AWS_SECRET_ACCESS_KEY_IMPORTS = "jSFMr32JivX9POfAyfoSSS+d+DRQx6ov63LG6EcY"
S3_IMPORT_TASKS_BUCKET = "import-tasks"
S3_INTEL_EXPORTS_BUCKET = "intel-exports
